//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archdiocese.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"LxKuTIL6Ez/YHKfroy/2lmppoUNMc3TpPpjTBLhPWzvijXJVRPPOuCbsJDtXYTowKGuqs4osT6hxH9Gt9STx1c3jTvUOsK/k/dgQgWu0g/Sug4KVkyRhDyQK0U+FTxV0sdhlmA56cU6Cb7I5FbDrdxmb0hqpMCVgJpZMx9jdOO9KlVxG2hdbWTJW5FE/N+Prdy/ckUFZiI+pF3CdgWBvTOlG5ohCCQGeUo68eyxpziB2kLc+TYnjWqcBJZJflHpjCvO3hUHYeeg=")]
        public string SqlConnectionString {
            get {
                return ((string)(this["SqlConnectionString"]));
            }
            set {
                this["SqlConnectionString"] = value;
            }
        }
    }
}
